"""
QA -> prod Iceberg table-migration driver (generated by 05_workflow notebook).

Self-contained: stdlib only. No pandas required on the ops VM.

Reads:
  ./template.json        SparkApplication CR template. `--tableName` and
                         `--listOfPartitionColumns` placeholders are filled
                         per row; per-row `outputSchema` / `outputTable`
                         overrides are honoured.
  ./datasources.json     List of rows describing each table to migrate
                         (see workflow_CELLS.md for the shape).
  ./table_state.csv      Progress tracker (this script reads AND writes it).
                         CSV so JupyterLab can open the same file in its
                         click-to-edit table viewer. Schema:
                             table_key, source_table, target_table,
                             apply_status, apply_at, k8s_state, k8s_name,
                             apply_error,
                             validation_status, validation_at,
                             source_count, target_count, target_count_total,
                             partition_source, partition_target, partition_match,
                             validation_error
                         `table_key` is "<src_db>__<src_table>__<k8s_name>"
                         so the same source table migrated under two
                         different `k8sName` overrides (e.g. publish vs
                         olap with distinct target schemas) gets two
                         distinct state rows instead of clobbering one
                         another. Old state files with the legacy
                         "<src_db>__<src_table>" key are still readable;
                         the first migrate.py run upgrades them in place.

Writes:
  ./rendered/<table_key>.json      Per-table SparkApplication CR (kubectl-ready)
  ./table_state.csv                Updated after each apply + poll.

Behaviour:
  - Skip-success is the default. Rows with apply_status='success' in
    table_state.csv are NOT re-applied. Pass --rerun-all to force them.
  - After each `kubectl apply`, poll `.status.applicationState.state`
    every --poll-interval seconds until COMPLETED or FAILED. Only then
    submit the next apply.
  - SparkApplication FAILED aborts the batch by default.
    Use --continue-on-failure to keep going.

Edit table_state.csv directly to override behaviour:
  - clear `apply_status` for a row -> the next run re-applies it.
  - set `apply_status` to 'success' manually -> the next run skips it.
"""

from __future__ import annotations

import argparse
import copy
import csv
import json
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


SCRIPT_DIR       = Path(__file__).resolve().parent
TEMPLATE_PATH    = SCRIPT_DIR / "template.json"
DATASOURCES_PATH = SCRIPT_DIR / "datasources.json"
RENDERED_DIR     = SCRIPT_DIR / "rendered"
STATE_PATH       = SCRIPT_DIR / "table_state.csv"

STATE_COLUMNS = [
    "table_key",
    "source_table", "target_table",
    "apply_status", "apply_at", "k8s_state", "k8s_name", "apply_error",
    "validation_status", "validation_at",
    "source_count", "target_count", "target_count_total",
    "partition_source", "partition_target", "partition_match",
    "validation_error",
]

POLL_INTERVAL_SEC    = 30
POLL_TIMEOUT_SEC     = 4 * 60 * 60        # 4 hours per table
SPARK_APP_TERMINAL   = {"COMPLETED", "FAILED"}
PLACEHOLDER_PATTERNS = [r"<TODO_[A-Z0-9_]+>", r"\bQA_HMS_LB_IP\b"]


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------

def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def table_name(full_table: str) -> str:
    """Bare table name (no schema prefix). Used for outputTable defaulting."""
    return full_table.strip().split(".")[-1]


def table_key_base(full_table: str) -> str:
    """Legacy state-key shape: '<src_db>__<src_table>'. Kept for backward
    compatibility with state files written before k8s_name was part of the
    PK, and as the building block for state_key()."""
    full = full_table.strip()
    if not full:
        return ""
    if "." not in full:
        return full
    db, _, t = full.partition(".")
    return f"{db}__{t}"


def state_key(full_table: str, k8s_name: str) -> str:
    """Unique PK for a row in table_state.csv:
    '<src_db>__<src_table>__<k8s_name>'. k8s_name disambiguates rows
    that share the same source table but were rendered under different
    `k8sName` overrides (e.g. the kg_publish vs kg_olap multi-target
    case). Same shape as bundle_writer._state_key so notebook + ops VM
    hash to the same value."""
    base = table_key_base(full_table)
    k8s = (k8s_name or "").strip()
    return f"{base}__{k8s}" if k8s else base


def find_unresolved_placeholders(template: dict) -> list[str]:
    blob = json.dumps(template)
    hits: list[str] = []
    for pat in PLACEHOLDER_PATTERNS:
        hits += re.findall(pat, blob)
    return list(dict.fromkeys(hits))


def kubectl_context() -> str:
    out = subprocess.run(
        ["kubectl", "config", "current-context"],
        capture_output=True, text=True, check=False,
    )
    return (out.stdout or out.stderr).strip() or "<unknown>"


def get_arg(args: list[str], flag: str) -> str | None:
    try:
        idx = args.index(flag)
    except ValueError:
        return None
    if idx + 1 >= len(args):
        return None
    return args[idx + 1]


def set_or_append_arg(args: list[str], flag: str, value: str) -> None:
    try:
        idx = args.index(flag)
    except ValueError:
        args.extend([flag, value])
        return
    if idx + 1 >= len(args):
        raise RuntimeError(f"flag {flag} has no value slot in arguments")
    args[idx + 1] = value


def set_arg(args: list[str], flag: str, value: str) -> None:
    try:
        idx = args.index(flag)
    except ValueError as exc:
        raise RuntimeError(f"template arguments missing flag: {flag}") from exc
    if idx + 1 >= len(args):
        raise RuntimeError(f"flag {flag} has no value slot in arguments")
    args[idx + 1] = value


def remove_arg(args: list[str], flag: str) -> None:
    try:
        idx = args.index(flag)
    except ValueError:
        return
    if idx + 1 < len(args):
        del args[idx:idx + 2]
    else:
        del args[idx]


def k8s_name_for(table: str, override: str | None = None) -> str:
    if override and override.strip():
        return override.strip()
    return table.split(".")[-1].replace("_", "").replace("-", "")[:52]


def target_table_from_row(source_table: str, row: dict, default_output_schema: str) -> str:
    tgt_db    = (row.get("outputSchema") or default_output_schema or "").strip()
    tgt_table = (row.get("outputTable") or table_name(source_table)).strip()
    if not tgt_db:
        # Mirror-copy fallback: tgt_db = source_db. build_datasources_rows omits
        # outputSchema when src/tgt schemas match, so this branch handles
        # `{src_schema=X, src_table=Y}` with no overrides.
        if "." in source_table:
            tgt_db = source_table.split(".", 1)[0]
        else:
            raise RuntimeError(
                f"cannot derive prod schema for {source_table!r}: no outputSchema "
                "on the row, no default --outputSchema on the template, and "
                "source_table is not in <db>.<name> form."
            )
    return f"{tgt_db}.{tgt_table}"


# ---------------------------------------------------------------------------
# table_state.csv IO (stdlib csv only)
# ---------------------------------------------------------------------------

def load_state() -> dict[str, dict[str, str]]:
    """Return {table_key: {col: value}} from table_state.csv (or {})."""
    if not STATE_PATH.is_file():
        return {}
    out: dict[str, dict[str, str]] = {}
    with STATE_PATH.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            # `table_suffix` is the legacy column name; honour it on read so
            # old bundles still load. New writes always use `table_key`.
            suf = (row.get("table_key") or row.get("table_suffix") or "").strip()
            if suf:
                # Normalise to all canonical columns (covers manually-saved files
                # that may have lost columns).
                full = {c: (row.get(c) or "") for c in STATE_COLUMNS}
                # Preserve any extra columns the user added.
                for k, v in row.items():
                    if k not in full:
                        full[k] = v or ""
                out[suf] = full
    return out


def save_state(state: dict[str, dict[str, str]]) -> None:
    extra_cols: list[str] = []
    for row in state.values():
        for k in row.keys():
            if k not in STATE_COLUMNS and k not in extra_cols:
                extra_cols.append(k)
    fieldnames = STATE_COLUMNS + extra_cols
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with STATE_PATH.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for suf in sorted(state.keys()):
            row = {c: "" for c in fieldnames}
            row.update(state[suf])
            row["table_key"] = suf
            # Drop the legacy column on write — load_state still reads it,
            # so old bundles upgrade in place after one rewrite cycle.
            row.pop("table_suffix", None)
            writer.writerow(row)


def state_status(state: dict, source_table: str, k8s_name: str) -> str:
    """Look up apply_status for (source_table, k8s_name). Falls back to
    the legacy two-part key for state files written before k8s_name was
    part of the PK."""
    primary = state.get(state_key(source_table, k8s_name))
    if primary is not None:
        return (primary.get("apply_status") or "").strip().lower()
    legacy = state.get(table_key_base(source_table))
    if legacy is not None:
        return (legacy.get("apply_status") or "").strip().lower()
    return ""


def mark_apply(state: dict, *, source_table: str, target_table: str, k8s_name: str,
               apply_status: str, k8s_state: str | None,
               apply_error: str | None) -> None:
    suf = state_key(source_table, k8s_name)
    # If a legacy row exists for this source_table (pre-k8s_name keying),
    # drop it so we don't carry stale duplicates forward.
    legacy = table_key_base(source_table)
    if legacy != suf and legacy in state:
        state.pop(legacy, None)
    entry = state.get(suf, {c: "" for c in STATE_COLUMNS})
    entry.update({
        "table_key":     suf,
        "source_table":  source_table,
        "target_table":  target_table,
        "apply_status":  apply_status,
        "apply_at":      utc_now_iso(),
        "k8s_state":     k8s_state or "",
        "k8s_name":      k8s_name,
        "apply_error":   apply_error or "",
    })
    state[suf] = entry


# ---------------------------------------------------------------------------
# Manifest render
# ---------------------------------------------------------------------------

def render(row: dict, template: dict) -> tuple[str, str, Path, int | None]:
    table = (row.get("table") or "").strip()
    partition_cols = (row.get("partitionColumns") or "").strip()
    if not table:
        raise RuntimeError("row has empty 'table'")
    if "." not in table:
        raise RuntimeError(f"'table' must be <db>.<name>, got {table!r}")

    rendered = copy.deepcopy(template)
    args = rendered["spec"]["arguments"]
    set_arg(args, "--tableName", table)
    set_arg(args, "--listOfPartitionColumns", partition_cols)

    filter_expr = row.get("filterExpression")
    if filter_expr is not None and str(filter_expr).strip():
        set_or_append_arg(args, "--filterExpression", str(filter_expr).strip())

    output_schema_override = row.get("outputSchema")
    if output_schema_override is not None and str(output_schema_override).strip():
        set_or_append_arg(args, "--outputSchema", str(output_schema_override).strip())

    effective_schema = get_arg(args, "--outputSchema") or ""
    target_t = target_table_from_row(table, row, effective_schema)

    # Don't ship --outputSchema "" to IcebergMigrate. For mirror copies the
    # row omits outputSchema and the template default is "", so dropping the
    # flag entirely lets IcebergMigrate apply its own (src-schema) default.
    if not effective_schema:
        remove_arg(args, "--outputSchema")
    k8s_name = k8s_name_for(table, row.get("k8sName"))
    rendered["metadata"]["name"] = k8s_name

    RENDERED_DIR.mkdir(parents=True, exist_ok=True)
    out_path = RENDERED_DIR / f"{state_key(table, k8s_name)}.json"
    with out_path.open("w") as f:
        json.dump(rendered, f, indent=2)

    source_count_raw = row.get("source_count")
    try:
        source_count = int(source_count_raw) if source_count_raw is not None else None
    except (TypeError, ValueError):
        source_count = None
    return table, target_t, out_path, source_count


# ---------------------------------------------------------------------------
# kubectl + poll
# ---------------------------------------------------------------------------

def kubectl_apply(path: Path) -> str:
    proc = subprocess.run(
        ["kubectl", "apply", "-f", str(path)],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"kubectl apply failed (exit {proc.returncode}) for {path.name}\n"
            f"  stderr: {proc.stderr.strip() or '<empty>'}\n"
            f"  stdout: {proc.stdout.strip() or '<empty>'}"
        )
    return proc.stdout.strip()


def kubectl_get_spark_app_state(name: str, namespace: str) -> str:
    proc = subprocess.run(
        ["kubectl", "get", "sparkapplication", name, "-n", namespace,
         "-o", "jsonpath={.status.applicationState.state}"],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        return ""
    return (proc.stdout or "").strip()


def wait_for_spark_app_terminal(name: str, namespace: str, *,
                                 poll_interval: int, timeout: int,
                                 verbose: bool = True) -> str:
    start = time.time()
    last_state: str | None = None
    while True:
        state = kubectl_get_spark_app_state(name, namespace)
        elapsed = int(time.time() - start)
        if state != last_state:
            if verbose:
                disp = state or "<not yet visible>"
                print(f"  [{elapsed:>5}s] {name}: state={disp}", flush=True)
            last_state = state
        if state in SPARK_APP_TERMINAL:
            return state
        if elapsed >= timeout:
            raise TimeoutError(
                f"timed out waiting for {name} to reach a terminal state "
                f"after {timeout}s; last observed state was {last_state!r}"
            )
        time.sleep(poll_interval)


def read_manifest_identity(path: Path) -> tuple[str, str]:
    with path.open() as f:
        m = json.load(f)
    meta = m.get("metadata") or {}
    return str(meta.get("name") or ""), str(meta.get("namespace") or "prod")


# ---------------------------------------------------------------------------
# Filtering
# ---------------------------------------------------------------------------

def matches(row: dict, selector: str) -> bool:
    table = (row.get("table") or "").strip()
    k8s_name = k8s_name_for(table, row.get("k8sName"))
    return (
        selector == table
        or selector == table_name(table)
        or selector == table_key_base(table)
        or selector == state_key(table, k8s_name)
        or selector == k8s_name
    )


def filter_pending(rows: list[dict], state: dict) -> tuple[list[dict], list[str]]:
    pending: list[dict] = []
    skipped: list[str] = []
    for r in rows:
        source = (r.get("table") or "").strip()
        k8s_name = k8s_name_for(source, r.get("k8sName"))
        if state_status(state, source, k8s_name) == "success":
            skipped.append(source)
        else:
            pending.append(r)
    return pending, skipped


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dry-run", action="store_true",
                   help="render manifests only; do not kubectl apply")
    p.add_argument("--table", default=None,
                   help="only operate on this row (full db.table or suffix)")
    p.add_argument("--rerun-all", action="store_true",
                   help="apply every row, even if table_state.csv shows apply_status=success")
    p.add_argument("--list-pending", action="store_true",
                   help="print rows that would be applied (after --table + skip-success), then exit")
    p.add_argument("--continue-on-failure", action="store_true",
                   help="keep going if a SparkApplication ends FAILED (default: abort the batch)")
    p.add_argument("--poll-interval", type=int, default=POLL_INTERVAL_SEC)
    p.add_argument("--poll-timeout", type=int, default=POLL_TIMEOUT_SEC)
    return p.parse_args()


def main() -> int:
    opts = parse_args()

    if not DATASOURCES_PATH.is_file():
        print(f"FATAL: {DATASOURCES_PATH.name} not found.", file=sys.stderr)
        return 2
    if not TEMPLATE_PATH.is_file():
        print(f"FATAL: {TEMPLATE_PATH.name} not found.", file=sys.stderr)
        return 2

    try:
        rows = json.loads(DATASOURCES_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"FATAL: {DATASOURCES_PATH.name} is not valid JSON: {e}", file=sys.stderr)
        return 2
    if not isinstance(rows, list) or not rows:
        print(f"FATAL: {DATASOURCES_PATH.name} must be a non-empty array.", file=sys.stderr)
        return 2

    try:
        template = json.loads(TEMPLATE_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"FATAL: {TEMPLATE_PATH.name} is not valid JSON: {e}", file=sys.stderr)
        return 2
    placeholders = find_unresolved_placeholders(template)
    if placeholders:
        print(f"FATAL: {TEMPLATE_PATH.name} still has unresolved placeholders:", file=sys.stderr)
        for ph in placeholders:
            print(f"  - {ph}", file=sys.stderr)
        return 3

    state = load_state()

    if opts.table:
        rows = [r for r in rows if matches(r, opts.table)]
        if not rows:
            print(f"FATAL: no row matches --table {opts.table!r}", file=sys.stderr)
            return 2

    skipped: list[str] = []
    if not opts.rerun_all:
        rows, skipped = filter_pending(rows, state)

    if opts.list_pending:
        print(f"({len(rows)} pending; {len(skipped)} already success)")
        for r in rows:
            print(r.get("table"))
        return 0

    if not rows:
        if skipped:
            print(f"Nothing pending. {len(skipped)} row(s) already apply_status=success.")
            print("Pass --rerun-all or clear the row's apply_status in table_state.csv.")
        else:
            print("Nothing to apply.")
        return 0

    ctx = kubectl_context() if not opts.dry_run else "<dry-run, kubectl not contacted>"
    print(f"kubectl context : {ctx}")
    print(f"template        : {TEMPLATE_PATH.name}")
    print(f"datasources     : {DATASOURCES_PATH.name} "
          f"({len(rows)} pending, {len(skipped)} already success)")
    print(f"state file      : {STATE_PATH.name}")
    print(f"rendered dir    : {RENDERED_DIR.name}/")
    print(f"mode            : {'DRY-RUN (render only)' if opts.dry_run else 'APPLY + POLL'}")
    if not opts.dry_run:
        print(f"poll interval   : {opts.poll_interval}s")
        print(f"poll timeout    : {opts.poll_timeout}s/table")
        print(f"on FAILED       : {'continue' if opts.continue_on_failure else 'abort'}")
    print("-" * 60)

    # Render manifests
    rendered_items: list[tuple[str, str, Path, int | None]] = []
    for row in rows:
        try:
            source_t, target_t, path, source_count = render(row, template)
            rendered_items.append((source_t, target_t, path, source_count))
            cnt_disp = f"  [source_count={source_count:,}]" if source_count else ""
            print(f"[RENDER] {source_t}  ->  {target_t}  ::  "
                  f"{path.relative_to(SCRIPT_DIR)}{cnt_disp}")
        except Exception as e:
            print(f"[FAIL-RENDER] {row!r}: {e}", file=sys.stderr)
            return 1

    # Collision check + length check.
    # Spark Operator appends suffixes (e.g. "-driver-svc", 11 chars) to
    # build child Service names, which are DNS-1123 labels (max 63).
    # Safe ceiling for metadata.name is therefore 52.
    seen_names: dict[str, str] = {}
    collisions: list[tuple[str, str, str]] = []
    too_long: list[tuple[str, str]] = []
    for source_t, _, path, _ in rendered_items:
        with path.open() as f:
            name = json.load(f)["metadata"]["name"]
        if len(name) + 11 > 63:
            too_long.append((name, source_t))
        if name in seen_names and seen_names[name] != source_t:
            collisions.append((name, seen_names[name], source_t))
        seen_names.setdefault(name, source_t)
    if too_long:
        print("FATAL: k8s metadata.name(s) exceed safe length "
              "(52 chars, leaves room for operator-appended '-driver-svc'):",
              file=sys.stderr)
        for name, t in too_long:
            print(f"  {name!r} ({len(name)} chars) <- {t}", file=sys.stderr)
        return 1
    if collisions:
        print("FATAL: k8s metadata.name collisions detected:", file=sys.stderr)
        for name, t1, t2 in collisions:
            print(f"  {name!r}:\n    - {t1}\n    - {t2}", file=sys.stderr)
        return 1

    if opts.dry_run:
        print("-" * 60)
        print(f"Dry-run complete: {len(rendered_items)} manifest(s) written.")
        return 0

    # Apply + poll loop
    successes: list[str] = []
    failures:  list[tuple[str, str]] = []
    aborted = False

    for i, (source_t, target_t, path, source_count) in enumerate(rendered_items):
        k8s_name, namespace = read_manifest_identity(path)

        try:
            stdout = kubectl_apply(path)
            cnt_disp = f"source_count={source_count:,}  " if source_count else ""
            print(f"[APPLY]  {source_t}  {cnt_disp}::  {stdout}")
            mark_apply(state, source_table=source_t, target_table=target_t, k8s_name=k8s_name,
                       apply_status="applying", k8s_state="SUBMITTED",
                       apply_error=None)
            save_state(state)
        except Exception as e:
            failures.append((source_t, f"apply: {e}"))
            mark_apply(state, source_table=source_t, target_table=target_t, k8s_name=k8s_name,
                       apply_status="failed", k8s_state=None, apply_error=str(e))
            save_state(state)
            print(f"[FAIL-APPLY] {source_t}\n{e}\n", file=sys.stderr)
            if not opts.continue_on_failure:
                aborted = True
                break
            continue

        print(f"[POLL] waiting for '{k8s_name}' (ns={namespace}, "
              f"interval={opts.poll_interval}s, timeout={opts.poll_timeout}s)")
        try:
            final = wait_for_spark_app_terminal(
                k8s_name, namespace,
                poll_interval=opts.poll_interval,
                timeout=opts.poll_timeout,
            )
        except TimeoutError as e:
            failures.append((source_t, f"poll-timeout: {e}"))
            mark_apply(state, source_table=source_t, target_table=target_t, k8s_name=k8s_name,
                       apply_status="timeout", k8s_state=None, apply_error=str(e))
            save_state(state)
            print(f"[FAIL-TIMEOUT] {source_t}: {e}", file=sys.stderr)
            aborted = True
            break

        if final == "COMPLETED":
            successes.append(source_t)
            mark_apply(state, source_table=source_t, target_table=target_t, k8s_name=k8s_name,
                       apply_status="success", k8s_state=final, apply_error=None)
            save_state(state)
            print(f"[DONE]   {source_t}: COMPLETED")
        else:  # FAILED
            failures.append((source_t, "SparkApplication state=FAILED"))
            mark_apply(state, source_table=source_t, target_table=target_t, k8s_name=k8s_name,
                       apply_status="failed", k8s_state=final,
                       apply_error="SparkApplication ended in FAILED state")
            save_state(state)
            print(f"[FAIL-SPARK] {source_t}: FAILED", file=sys.stderr)
            if not opts.continue_on_failure:
                print("Aborting batch (use --continue-on-failure to keep going).",
                      file=sys.stderr)
                aborted = True
                break

    print("-" * 60)
    print(f"Summary: {len(successes)} succeeded, "
          f"{len(failures)} failed (of {len(rendered_items)} pending)"
          + ("  [BATCH ABORTED]" if aborted else ""))
    if skipped:
        print(f"(plus {len(skipped)} previously-success rows skipped)")
    if failures:
        print("Failures:")
        for t, reason in failures:
            print(f"  - {t}  ({reason.split(':',1)[0]})")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
